import type { LeadListItem } from "./types";

export const MOCK_LEADS: LeadListItem[] = [
  {
    id: "lead-001",
    createdAt: "2026-03-08T09:14:00.000Z",
    fullName: "Stefan Mertens",
    email: "stefan.mertens@example.de",
    phone: "+49 170 1234567",
    service: "Getriebespülung",
    sourceLabel: "Kontaktformular",
    sourcePage: "/kontakt",
    type: "contact",
    formKey: "contact-form",
    status: "NEW",
    source: "wordpress",
  },
  {
    id: "lead-002",
    createdAt: "2026-03-07T14:32:00.000Z",
    fullName: "Maria Gh",
    email: "",
    phone: "+49 2234 6889977",
    service: "Reifenservice",
    sourceLabel: "WhatsApp Widget",
    sourcePage: "/",
    type: "whatsapp",
    formKey: "whatsapp",
    status: "READ",
    source: "wordpress",
  },
  {
    id: "lead-003",
    createdAt: "2026-03-07T11:05:00.000Z",
    fullName: "Peter Füssenich",
    email: "p.fuessenich@example.de",
    phone: "+49 171 9876543",
    service: "KFZ Service",
    sourceLabel: "Leistungs-Anfrage",
    sourcePage: "/kfz-service",
    type: "service",
    formKey: "service-inquiry",
    status: "READ",
    source: "wordpress",
  },
  {
    id: "lead-004",
    createdAt: "2026-03-06T16:48:00.000Z",
    fullName: "Anonym (Anruf)",
    email: "",
    phone: "+49 160 5551234",
    service: "Reifenservice",
    sourceLabel: "Anruf-Button",
    sourcePage: "/reifenservice",
    type: "phone",
    formKey: "phone",
    status: "ARCHIVED",
    source: "wordpress",
  },
  {
    id: "lead-005",
    createdAt: "2026-03-05T08:22:00.000Z",
    fullName: "Joachim Wolf",
    email: "joachim.wolf@example.de",
    phone: "",
    service: "Klimaservice",
    sourceLabel: "E-Mail Link",
    sourcePage: "/kontakt",
    type: "contact",
    formKey: "email",
    status: "READ",
    source: "wordpress",
  },
];
